[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200

upload_protocol = custom
upload_command = C:\Users\Michal-Janocha\.platformio\packages\tool-dfuutil-arduino\dfu-util.exe -d 0x2341:0x0366 -a 0 -s 0x08040000:leave -D $SOURCE
